doc: fix sphinx build
- make regex expressions raw strings
- fix double reference to AppDevGuide
- remove unused static_html setting
- improve get_seq_release() in conf.py
- use Pillow<10.0.0, resolving the
  AttributeError: 'ImageDraw' ... in blockdiag
- install dependencies for Pillow<10.0.0